<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>io.github.persiliao</groupId>
        <artifactId>mqtt-spring-boot-starter-parent</artifactId>
        <version>3.0.0</version>
    </parent>
    <version>3.0.0</version>
    <artifactId>mqtt-spring-boot-starter</artifactId>
    <name>Mqtt Spring Boot Starter</name>
    <description>Starter for Mqtt with auto-configuration</description>

    <url>https://github.com/persiliao/mqtt-spring-boot-starter</url>

    <licenses>
        <license>
            <name>MIT License</name>
            <url>https://opensource.org/licenses/MIT</url>
            <distribution>repo</distribution>
        </license>
    </licenses>

    <developers>
        <developer>
            <id>persiliao</id>
            <name>Persi.Liao</name>
            <email>xiangchu.liao@gmail.com</email>
            <organization>persiliao</organization>
            <organizationUrl>https://github.com/persiliao</organizationUrl>
        </developer>
    </developers>

    <scm>
        <connection>scm:git:https://github.com/persiliao/mqtt-spring-boot-starter.git</connection>
        <developerConnection>scm:git:https://github.com/persiliao/mqtt-spring-boot-starter.git</developerConnection>
        <url>https://github.com/persiliao/mqtt-spring-boot-starter</url>
    </scm>
    
    <dependencies>
        <dependency>
            <groupId>io.github.persiliao</groupId>
            <artifactId>mqtt-spring-boot-autoconfigure</artifactId>
            <version>3.0.0</version>
        </dependency>
    </dependencies>
</project>
