<?xml version="1.0" encoding="UTF-8"?>
<project xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns="http://maven.apache.org/POM/4.0.0"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>io.github.persiliao</groupId>
        <artifactId>spring-boot-starter</artifactId>
        <version>3.0.1</version>
        <relativePath/> <!-- lookup parent from repository -->
    </parent>

    <groupId>io.github.persiliao</groupId>
    <artifactId>mqtt-spring-boot-starter-parent</artifactId>
    <version>3.0.0</version>
    <packaging>pom</packaging>

    <name>Mqtt Spring Boot Starter Parent</name>
    <description>Parent POM for Mqtt Spring Boot Starter</description>
    <url>https://github.com/persiliao/mqtt-spring-boot-starter</url>

    <properties>
        <hivemq.version>1.3.13</hivemq.version>
        <jetbrains.annotations.version>13.0</jetbrains.annotations.version>
    </properties>

    <modules>
        <module>mqtt-spring-boot-autoconfigure</module>
        <module>mqtt-spring-boot-starter</module>
    </modules>

    <dependencyManagement>
        <dependencies>
            <dependency>
                <groupId>io.github.persiliao</groupId>
                <artifactId>mqtt-spring-boot-autoconfigure</artifactId>
                <version>${project.version}</version>
            </dependency>

            <dependency>
                <groupId>io.github.persiliao</groupId>
                <artifactId>mqtt-spring-boot-starter</artifactId>
                <version>${project.version}</version>
            </dependency>
        </dependencies>
    </dependencyManagement>
</project>
